# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'antiplagio.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(685, 733)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButtonAddFile = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonAddFile.setGeometry(QtCore.QRect(40, 200, 191, 31))
        self.pushButtonAddFile.setObjectName("pushButtonAddFile")
        self.pushButtonExecute = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonExecute.setGeometry(QtCore.QRect(490, 547, 151, 31))
        self.pushButtonExecute.setObjectName("pushButtonExecute")
        self.labelFileName_2 = QtWidgets.QLabel(self.centralwidget)
        self.labelFileName_2.setGeometry(QtCore.QRect(290, 260, 341, 21))
        self.labelFileName_2.setText("")
        self.labelFileName_2.setObjectName("labelFileName_2")
        self.labelExecute = QtWidgets.QLabel(self.centralwidget)
        self.labelExecute.setGeometry(QtCore.QRect(40, 510, 591, 16))
        self.labelExecute.setObjectName("labelExecute")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(210, 30, 301, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 590, 611, 20))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(200, 620, 231, 20))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(280, 650, 91, 16))
        self.label_4.setObjectName("label_4")
        self.pushButton_DeleteFile = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_DeleteFile.setGeometry(QtCore.QRect(490, 447, 151, 31))
        self.pushButton_DeleteFile.setObjectName("pushButton_DeleteFile")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(40, 490, 601, 16))
        self.label_5.setObjectName("label_5")
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(40, 240, 601, 192))
        self.listWidget.setObjectName("listWidget")
        self.pushButtonAddFileOriginal = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonAddFileOriginal.setGeometry(QtCore.QRect(40, 90, 191, 31))
        self.pushButtonAddFileOriginal.setObjectName("pushButtonAddFileOriginal")
        self.fileWidget = QtWidgets.QListWidget(self.centralwidget)
        self.fileWidget.setGeometry(QtCore.QRect(40, 130, 601, 51))
        self.fileWidget.setObjectName("fileWidget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 685, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Cходство между файлами"))
        self.pushButtonAddFile.setText(_translate("MainWindow", "Добавить документов"))
        self.pushButtonExecute.setText(_translate("MainWindow", "Поиск сходства"))
        self.labelExecute.setText(_translate("MainWindow", "Панель выполнения"))
        self.label.setText(_translate("MainWindow", "Сравнение документов"))
        self.label_2.setText(_translate("MainWindow", "Инструментальное программное обеспечение разработки и проектирования информационных систем"))
        self.label_3.setText(_translate("MainWindow", "ИКМО 01-20     Ранди Реина Эрнандес"))
        self.label_4.setText(_translate("MainWindow", "Москва 2021"))
        self.pushButton_DeleteFile.setText(_translate("MainWindow", "Удалить документ"))
        self.label_5.setText(_translate("MainWindow", "------------------------------------------------------------------------------------------------------------------------"))
        self.pushButtonAddFileOriginal.setText(_translate("MainWindow", "Добавить документ"))
